config/routes.rb
MethodologyApp::Application.routes.draw do
  get "libraries/index"

  devise_for :users
  namespace :admin do
    post 'users/import'
  end
  resource :account, :only => [:edit, :update]
  resources :users

  resources :projects, :shallow => true do
    member do
      get 'library'
    end
    
    resources :events do
      resources :comments
      resources :documents
    end
    resources :tasks do
      resources :comments
    end
  end
  get 'projects/:id/versions' => 'versions#project', :as => :project_versions
  get "projects_status/index"
  resources :reports, :only => [:index, :new]
  resources :project_names
  
  resources :holidays
  
  resources :org_units

  get "methodology/index"
  
  root :to => "projects#index"
  

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  
  include DateUtils
  
  validates :name, :presence => true
  validates :date, :presence => true, :uniqueness => true 
  
  scope :in_year, lambda {|year| where(['year(date) = ?', year]) }
  scope :this_year, in_year(Date.today.year)
  scope :ordered, order(:date)
  
  attr_accessible :name, :date
  date_writer_for :date
  
end

app/controllers/admin/holidays_controller.rb
class Admin::HolidaysController < ApplicationController
  
  before_filter :basic_authenticate
  
  def index
    @holidays = Holiday.this_year.ordered
  end
  
  def new
    @holiday = Holiday.new
  end
  
  def create
    @holiday = Holiday.new(params[:holiday])
    
    if @holiday.save
      redirect_to(admin_holidays_path, :notice => "#{Holiday.model_name.human.humanize} creado")
    else
      render :action => :new
    end
  end
  
  def edit
    @holiday = Holiday.find(params[:id])
  end
  
  def update
    @holiday = Holiday.find(params[:id])
    
    if @holiday.update_attributes(params[:holiday])
      redirect_to(admin_holidays_path, :notice => "#{Holiday.model_name.human.humanize} actualizado")
    else
      render :action => :edit
    end
  end
  
  def destroy
    Holiday.delete(params[:id])
    redirect_to(admin_holidays_path, :notice => "#{Holiday.model_name.human.humanize} eliminado")
  end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_boss_logged_in
  
  def index
    @holidays = Holiday.this_year.ordered
  end
  
  def new
    @holiday = Holiday.new
  end
  
  def create
    @holiday = Holiday.new(params[:holiday])
    
    if @holiday.save
      redirect_to(holidays_path, :notice => "#{Holiday.model_name.human.humanize} creado")
    else
      render :action => :new
    end
  end
  
  def edit
    @holiday = Holiday.find(params[:id])
  end
  
  def update
    @holiday = Holiday.find(params[:id])
    
    if @holiday.update_attributes(params[:holiday])
      redirect_to(holidays_path, :notice => "#{Holiday.model_name.human.humanize} actualizado")
    else
      render :action => :edit
    end
  end
  
  def destroy
    Holiday.delete(params[:id])
    redirect_to(holidays_path, :notice => "#{Holiday.model_name.human.humanize} eliminado")
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.haml
= content_for :head do
  = javascript_include_tag 'jquery-ui-1.8.12.custom.min', 'jquery.ui.datepicker-es'
  = stylesheet_link_tag 'jquery-ui-1.8.12.custom'
  :javascript
    $(document).ready(function() {
      $('#holiday_date').datepicker();
    });

= form.error_messages :header_message => nil, :message => nil

%p
  = form.label(:name)
  %br/
  = form.text_field(:name)

%p
  = form.label(:date)
  %br/
  = form.text_field(:date, :size => 27, :value => date_default_value(@holiday.date))

app/views/holidays/_holiday.html.haml
%li 
  [#{l(holiday.date)}] - #{holiday.name}
  = link_to(image_tag("edit.png", :border => 0), edit_holiday_path(holiday))
  &nbsp;|&nbsp;
  = link_to(image_tag("delete.png", :border => 0), holiday_path(holiday), 
            :method => :delete, :confirm => "¿Está seguro que desea eliminar el #{Holiday.model_name.human}?")

app/views/holidays/_list.html.haml
%ol
  = render list

app/views/holidays/_sidebar.html.haml
#sidebar
  %ul
    %li
      %h2 Menú
      %ul
        - if controller.action_name == 'index'
          %li
            = link_to 'Nuevo', new_holiday_path
        - else
          %li
            = link_to Holiday.model_name.human.pluralize.humanize, holidays_path
        %li
          = link_to 'Volver', :back
/ end #sidebar

app/views/holidays/edit.html.haml
= content_for :title, "Editando #{Holiday.model_name.human}"
= content_for :sidebar, render('sidebar')

= form_for @holiday do |f|
  = render f
  = f.submit 'Actualizar'

app/views/holidays/index.html.haml
= content_for :title, "Listando #{Holiday.model_name.human.pluralize}"
= content_for :sidebar, render('sidebar')

- if @holidays.empty?
  = not_found(Holiday)
- else
  = render 'list', :list => @holidays

app/views/holidays/new.html.haml
= content_for :title, "Nuevo #{Holiday.model_name.human}"
= content_for :sidebar, render('sidebar')

= form_for @holiday do |f|
  = render f
  = f.submit 'Crear'