config/routes.rb
MethodologyApp::Application.routes.draw do
  get "libraries/index"

  devise_for :users
  namespace :admin do
    post 'users/import'
  end
  resource :account, :only => [:edit, :update]
  resources :users

  resources :projects, :shallow => true do
    member do
      get 'library'
    end
    
    resources :events do
      resources :comments
      resources :documents
    end
    resources :tasks do
      resources :comments
    end
  end
  get 'projects/:id/versions' => 'versions#project', :as => :project_versions
  get "projects_status/index"
  resources :reports, :only => [:index, :new]
  resources :project_names
  
  resources :holidays
  
  resources :org_units

  get "methodology/index"
  
  root :to => "projects#index"
  

end

app/views/shared/_email_verif_alert.html.haml
- unless current_user.email
  %p
    %h3
      Por favor, verifique su
      = link_to 'email', edit_account_path

app/views/shared/_menu.html.haml
#menu
  %ul
    - if user_signed_in?
      %li.current_page_item.first
        = link_to Project.model_name.human.humanize.pluralize, projects_path
      - if boss_or_dev_logged_in?
        %li
          = link_to 'Nomenclatura', project_names_path
        %li
          = link_to OrgUnit.model_name.human.pluralize.humanize, org_units_path
        %li
          = link_to User.model_name.human.pluralize.humanize, users_path
      /
        %li
          = link_to Holiday.model_name.human.humanize.pluralize, holidays_path
      %li
        = link_to 'Metodología', methodology_index_path
      %li
        = link_to 'Salir', destroy_user_session_path
      %li.current_page_item.first.right
        = link_to current_user.username.upcase, edit_account_path
    - else
      %li.current_page_item.first
        = link_to 'Ingresar', new_user_session_path
/ end #menu