config/routes.rb
MethodologyApp::Application.routes.draw do
  get "libraries/index"

  devise_for :users
  namespace :admin do
    post 'users/import'
  end
  resource :account, :only => [:edit, :update]
  resources :users

  resources :projects, :shallow => true do
    member do
      get 'library'
    end
    
    resources :events do
      resources :comments
      resources :documents
    end
    resources :tasks do
      resources :comments
    end
  end
  get 'projects/:id/versions' => 'versions#project', :as => :project_versions
  get "projects_status/index"
  resources :reports, :only => [:index, :new]
  resources :project_names
  
  resources :holidays
  
  resources :org_units

  get "methodology/index"
  
  root :to => "projects#index"
  

end

app/models/project.rb
# coding: utf-8

class Project < ActiveRecord::Base
  class Status
    NEW = 1
    IN_DEV = 2
    STOPPED = 3
    CANCELED = 4
    FINISHED = 5
    
    SELECT = [['Nuevo', NEW], ['En desarrollo', IN_DEV], ['Detenido', STOPPED], 
              ['Cancelado', CANCELED], ['Terminado', FINISHED]]
  end
  
  class Klass
    DEV = 1
    IMPR = 2
    PROC = 3
    
    SELECT = [['Desarrollo', DEV], ['Valorización', IMPR], ['Proceso', PROC]]
  end
  
  class Indicator
    ON_COURSE = 1
    PENDING = 2
    NOT_STARTED = 3
    NOT_FINISHED = 4
    FINISHED = 5
    COMMITTED = 6
    
    SELECT = [['En curso', ON_COURSE], ['Pendiente', PENDING], ['No iniciado', NOT_STARTED], 
             ['No finalizado', NOT_FINISHED], ['Finalizado', FINISHED], ['Comprometido', COMMITTED]]
    
    class << self
      def to_s(indicator)
        arr = SELECT.find {|arr| arr.last == indicator}
        arr.first if arr
      end
    end
  end

  has_paper_trail :only => [:envisaged_end_date]

  include DateUtils
  include AsyncEmail
  include Duration
  
  belongs_to :owner, :class_name => 'User'
  belongs_to :dev, :class_name => 'User', :foreign_key => :dev_id
  belongs_to :updater, :class_name => 'User', :foreign_key => :updated_by
  belongs_to :project_name
  belongs_to :org_unit
  has_many :events, :dependent => :destroy, :order => 'id desc'
  has_many :tasks, :dependent => :destroy do
    def list(options={})
      t = options.has_key?(:show_all) ? scoped : incomplete
      t.ordered.page(options[:page]).per(10)
    end
  end
  has_and_belongs_to_many :users

  validates :req_nbr, :numericality => { :greater_than => 0, 
                                         :message => I18n.t('errors.messages.blank') },
                      :uniqueness => { :allow_nil => true }
  validates :compl_perc, :numericality => { :greater_than_or_equal_to => 0, 
                                            :message => I18n.t('errors.messages.blank') }
  validates :klass, :numericality => { :greater_than => 0, 
                                       :message => I18n.t('errors.messages.blank') }
  validates :dev_id, :numericality => { :greater_than => 0, 
                                        :message => I18n.t('errors.messages.blank') }
  validates :owner_id, :numericality => { :greater_than => 0, 
                                          :message => I18n.t('errors.messages.blank') }
  validates :project_name_id, :numericality => { :greater_than => 0, 
                                                 :message => I18n.t('errors.messages.blank') }
  validates :org_unit_id, :numericality => { :greater_than => 0, 
                                             :message => I18n.t('errors.messages.blank') }
  validates :estimated_start_date, :presence => true
  validates :estimated_end_date, :presence => true
  validates :estimated_duration, :numericality => { :greater_than => 0 }
  validates :requirement, :presence => true
  validate :dates_set
  validate :devs_and_owners_email_address
  validate :owner_not_among_users
  
  def indicator_class_for(project)
    return 'green' if project.started_on <= Date.today &&  project.in_dev?
    return 'yellow' if project.estimated_start_date > Date.today
    return 'red' if project.estimated_start_date < Date.today && project.new?
    return 'black' if project.estimated_end_date < Date.today && ! project.finished?
    return 'blue' if project.finished?
  end
  
  scope :on_course, lambda { where(:started_on <= Date.today, :status => Status::IN_DEV) }
  scope :pending, lambda { where(:estimated_start_date > Date.today, :status => Status::NEW) }
  scope :not_started, lambda { where(:estimated_start_date < Date.today, :status => Status::NEW) }
  scope :not_finished, lambda { committed.where(:estimated_end_date < Date.today) }
  scope :finished, lambda { where(:status => Status::FINISHED) }
  scope :ordered, order(:req_nbr.desc)
  scope :developed_by, lambda { |dev_id| where(:dev_id => dev_id) }
  scope :upcoming, lambda { where(:status => Status::NEW) }
  scope :on_est_course_by, lambda { |date| where(['? between estimated_start_date and estimated_end_date', date]) }
  scope :on_course_by, lambda { |date| where(['? between estimated_start_date and envisaged_end_date', date]) }
  scope :committed, where(:status.not_in => [Status::CANCELED, Status::FINISHED])
  scope :compl_perc_has_not_been_updated_since_last_week, lambda { joins(:dev).
                                                                   where(:dev => {:username => Conf.devs.split(',')}).
                                                                   where(:last_compl_perc_update_at < 1.week.ago) }

  before_create :touch_last_compl_perc_update
  before_save :set_default_envisaged_end_date
  after_update :create_first_event
  after_update :stop_current_event
  after_save :notify_project_saved
  
  cattr_reader :per_page
  @@per_page = 20
  attr_reader :user_tokens, :notify_envisaged_end_date_changed
  attr_writer :notify_envisaged_end_date_changed
  attr_accessor :indicator
  attr_accessible :description, :dev_id, :owner_id, :user_ids, :estimated_start_date, :estimated_end_date, 
                  :estimated_duration, :status, :updated_by, :user_tokens, :compl_perc, :klass, :indicator, 
                  :envisaged_end_date, :estimated_duration_unit, :project_name_id, :requirement, 
                  :org_unit_id, :req_nbr, :notify_envisaged_end_date_changed
  date_writer_for :estimated_start_date, :estimated_end_date, :envisaged_end_date
  
  class << self
    def search(template, options = {})
      projects = scoped
      
      if template.project_name_id.present?
        projects = projects.where(:project_name_id => ProjectName.subtree_of(template.project_name_id).map(&:id))
      end
      
      [:dev_id, :owner_id].each { |col|
        projects = projects.where(col => template.send(col)) if template.send(col).present?
      }
    
      projects = projects.where(:started_on >= template.started_on) if template.started_on.present?
      projects = projects.where(:estimated_end_date <= template.estimated_end_date) if template.estimated_end_date.present?
    
      if template.indicator.present?
        arr = Project::Indicator.constants.map {|const| const.to_s.downcase}.sort
        arr.pop
        arr.each { |ind| projects = projects.send(ind) if template.indicator.to_i == "Project::Indicator::#{ind.upcase}".constantize }
      end
    
      if options[:order]
        projects = projects.order(options[:order])
      else
        projects = projects.ordered
      end
      
      projects.page(options[:page]).per(per_page)
    end
    
    def search_for(user)
      if user.dev?
        projects = developed_by(user.id)
      else
        projects = scoped
      end
    
      projects_by_dev = projects.on_course.includes(:dev, :events, :project_name).group_by(&:dev)
      
      projects_by_dev.keys.sort{|dev1, dev2| dev1.name <=> dev2.name}.map { |dev|
        projects_by_dev[dev].sort{|pr1, pr2| pr2.req_nbr <=> pr1.req_nbr}
      }.flatten
    end
    
    def by_dev
      projects_by_dev = {}
      keys = [:on_course, :pending, :stopped]
      
      committed_by_dev = committed.includes(:dev, :project_name).group_by(&:dev)
      devs = committed_by_dev.keys.sort{|dev1, dev2| dev1.name <=> dev2.name}
      
      devs.each do |dev|
        projects_by_dev[dev] = {}
        keys.each { |key| projects_by_dev[dev][key] = [] }
        
        committed_by_dev[dev].each do |project|
          keys.each do |key| 
            if project.send("#{key}?")
              projects_by_dev[dev][key] << project
              break
            end
          end
        end
      end
      projects_by_dev.each do |dev, projects|
        projects[:on_course].sort! { |pr1, pr2| pr1.started_on <=> pr2.started_on }
        projects[:pending].sort! { |pr1, pr2| pr1.estimated_start_date <=> pr2.estimated_start_date }
      end
    end
    
    def notify_devs_compl_perc_has_not_been_updated_since_last_week
      on_course.compl_perc_has_not_been_updated_since_last_week.order(:last_compl_perc_update_at).
                group_by(&:dev).each { |dev, projects|
        Notifications.compl_perc_has_not_been_updated_since_last_week(dev, projects).deliver
      }
    end
    
    def library
      Project.includes([:project_name, {:events => :documents}]).
                        order(:req_nbr.desc, :documents => [:event_id.desc, :created_at.desc]).all.
                        select {|project| ! project.documents.empty?}
    end
  end
  
  def user_tokens=(ids)
    self.user_ids = ids.split(",")
  end
  
  def to_s
    "##{req_nbr} - [#{project_name}] - #{requirement.humanize}"
  end
  
  def all_users
    users(true).to_a.push(dev, owner)
  end
  
  def attributes=(attrs)
    keys = [:status, :compl_perc]
    if keys.any? { |key| attrs.has_key?(key) }
      updated_by_dev = attrs[:updated_by].to_i == (attrs.has_key?(:dev_id) ? attrs[:dev_id].to_i : dev.id)
      if !updated_by_dev || (attrs[:status].to_i == Status::FINISHED && new?)
        keys.each { |key| attrs.delete(key) }
      end
    end
    
    # unless (attrs.has_key?(:status) ? attrs[:status].to_i : status) == Status::NEW
    #   cols = Project.column_names.map(&:to_sym)
    #   cols.delete(:compl_perc)
    #   cols.delete(:status)
    #   cols.delete(:envisaged_end_date)
    #   cols.each { |col| attrs.delete(col) }
    # end
    
    if [Status::NEW, Status::FINISHED].include?(attrs.has_key?(:status) ? attrs[:status].to_i : status)
      attrs.delete(:compl_perc)
    end
    
    super
    
    @notify_envisaged_end_date_changed = attrs[:notify_envisaged_end_date_changed].to_i == 1 && envisaged_end_date_changed? && persisted?
    
    if new? && estimated_duration
      self.estimated_end_date = in_days(self, :estimated_duration).business_days.after(estimated_start_date-1).to_date
    end
  end
  
  def status=(stat)
    if stat.to_i == Status::IN_DEV
      self.started_on = Date.today unless started_on

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @project = Project.new
    @projects = Project.search_for(current_user)
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    
    if @project.save
      redirect_to @project, :notice => "#{Project.model_name.human.humanize} creado"
    else
      render :action => :new
    end
  end
  
  def show
    @project = Project.find(params[:id], :include => [:dev, :users, :project_name, {:org_unit => :parent}])
  end

  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    
    if @project.update_attributes(params[:project].merge(:updated_by => current_user.id))
      redirect_to @project, :notice => "#{Project.model_name.human.humanize} actualizado"
    else
      render :action => :edit
    end
  end
  
  def destroy
    Project.destroy(params[:id])
    redirect_to projects_path, :notice => "#{Project.model_name.human.humanize} eliminado"
  end
  
  def library
    @project = Project.find(params[:id], :include => [:events => :documents])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def potential_project_names(project_names)
    project_names.map do |project_name, children|
      children.empty? ? render('project_name', :project_name => project_name) : potential_project_names(children)
    end.join('<br/>').html_safe
  end
  
  def indicator_for(project)
    image_tag("#{project.status_indicator}.png", :border => 0)
  end
end

app/views/projects/_document.html.haml
%li
  = link_to document.name, document
  = link_to image_tag('down.png', :border => 0), document.file.url
  [#{l(document.created_at, :format => :short)}]

app/views/projects/_form.html.haml
= content_for :head do
  = javascript_include_tag 'jquery-ui-1.8.12.custom.min', 'jquery.ui.datepicker-es', 'jquery.tokeninput', 'jquery.chained'
  = stylesheet_link_tag 'jquery-ui-1.8.12.custom', 'token-input-facebook'
  :javascript
    $(document).ready(function() {
      $('#project_estimated_start_date').datepicker();
      // $('#project_estimated_end_date').datepicker();
      $('#project_envisaged_end_date').datepicker();
      $("#project_user_tokens").tokenInput("#{users_path(:format => :json)}", {
        crossDomain: false,
        prePopulate: $("#project_user_tokens").data("pre"),
        theme: "facebook"
      });
      
      /*$('#project_estimated_start_date').change(function() {
        $('#project_estimated_end_date').datepicker('setDate', addDaysTo($(this).datepicker('getDate'), 1));
      });*/
      
      if(#{@project.persisted?}) {
        $('#project_envisaged_end_date').change(function() {
          $('#notify_envisaged_end_date_changed').show();
        });
      }
      
      $("#project_name_id1").chained("#project_name_id0");
      $("#project_name_id2").chainedTo("#project_name_id1");
      
      arr = [#{@project.project_name_id ? @project.project_name.path_ids.join(',') : ''}]
      if(arr.length > 0) {
        $("#project_name_id0").val(arr[0]);
        $("#project_name_id0").change();
      }
      if(arr.length > 1) {
        $("#project_name_id1").val(arr[1]);
        $("#project_name_id1").change();
      }
      if(arr.length > 2)
        $("#project_name_id2").val(arr[2]);
        
      $('form#project_form').submit(function(e){
           e.preventDefault(); //Prevent the normal submission action
           validate_project_name(this);
      });
    });
    
    function validate_project_name(form) {
      if($("#project_name_id2").attr('disabled'))
        if($("#project_name_id1").attr('disabled'))
          value = $("#project_name_id0").val();
        else
          value = $("#project_name_id1").val();
      else
        value = $("#project_name_id2").val();
        
      if(value.length == 0)
        alert("Debe seleccionar un nombre de proyecto");
      else {
        $("#project_project_name_id").val(value);
        form.submit();
      }
    }
    

= form.error_messages :header_message => nil, :message => nil

/- if @project.new?
= form.hidden_field :project_name_id

%table.bottom_spaced{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
  %tr
    %td{:width => '20%'}
      %strong= form.label :req_nbr
    %td{:width => '80%'}
      %strong= form.label :project_name_id
  %tr
    %td{:width => '20%'}
      = form.text_field :req_nbr, :size => 3
    %td{:width => '80%'}
      = select_tag :project_name_id0, options_for_select(ProjectName.at_depth(0).ordered.map{|pn| [pn.text, pn.id]}), :include_blank => true
      = select_tag :project_name_id1, options_for_select(ProjectName.at_depth(1).ordered.map{|pn| [pn.text, pn.id, {:class => pn.parent_id}]}), :include_blank => true
      = select_tag :project_name_id2, options_for_select(ProjectName.at_depth(2).ordered.map{|pn| [pn.text, pn.id, {:class => pn.parent_id}]}), :include_blank => true

%p
  %strong= form.label :org_unit_id
  %br/
  = form.collection_select :org_unit_id, OrgUnit.not_roots.with_parent, :id, :to_s, :include_blank => true

%p
  %strong= form.label :requirement
  %br/
  = form.text_field :requirement, :size => 48

%p
  %strong= form.label :description
  %br/
  = form.text_area :description, :cols => 55, :rows => 5

%table.bottom_spaced{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
  %tr
    %td{:width => '33.3%'}
      %strong= form.label :dev_id
    %td{:width => '33.3%'}
      %strong= form.label :owner_id
    %td{:width => '33.3%'}
      %strong= form.label :klass
  %tr
    %td{:width => '33.3%'}
      = form.collection_select :dev_id, User.devs, :id, :name, :include_blank => true
    %td{:width => '33.3%'}
      = form.collection_select :owner_id, User.potential_owners, :id, :name, :include_blank => true
    %td{:width => '33.3%'}
      = form.select :klass, options_for_select(Project::Klass::SELECT, controller.action_name == 'new' ? nil : @project.klass), 
                :include_blank => controller.action_name == 'new'
                  
%p
  %strong= form.label :user_ids
  %br/
  = form.text_field :user_tokens, "data-pre" => @project.users.map(&:attributes).to_json

%table.bottom_spaced{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
  %thead
    %tr
      %td{:colspan => 3}
        %em Estimación
  %tbody
    %tr
      %td{:width => '33.3%'}
        %strong= form.label :estimated_start_date
      %td{:width => '33.3%'}
        %strong= form.label :estimated_duration
      %td{:width => '33.3%'}
        %strong= form.label :estimated_end_date
    %tr
      %td{:width => '33.3%'}
        = form.text_field :estimated_start_date, :size => 27, 
                          :value => date_default_value(@project.estimated_start_date)
      %td{:width => '33.3%'}
        = form.text_field :estimated_duration, :size => 4
        = duration_options_for(@project, :estimated_duration_unit)
      %td{:width => '33.3%'}
        = form.text_field :estimated_end_date, :size => 27, 
                          :value => date_default_value(@project.estimated_end_date),
                          :disabled => true

app/views/projects/_list.html.haml
- if list.empty?
  %p= not_found(Project)
- else
  %table.pretty{:border => 0, :cellpadding => 2, :cellspacing => 2, :width => '100%'}
    %thead
      %tr
        %th 
        %th N°
        %th Fecha
        %th Projecto
        %th Objetivo
        %th Tipo
        - unless current_user.dev?
          %th Analista
        %th Etapa
        %th Estado
        %th % Avance
        %th Fin previsto
    %tbody
    - list.each do |project|
      %tr
        %td= indicator_for(project)
        %td= link_to("##{project.req_nbr}", project)
        %td= l(project.created_at, :format => :tiny)
        %td= project
        %td
          = truncate(project.description.humanize, :length => 25) if project.description.present?
        %td= project.klass_str.first.upcase
        - unless current_user.dev?
          %td= project.dev.name
        %td= project.events.first ? project.events.first.stage_str : nil
        %td= project.events.first ? project.events.first.status_str : nil
        %td #{project.compl_perc} %
        %td= l(project.envisaged_end_date, :format => :tiny)

app/views/projects/_project_name.html.haml
= radio_button_tag "project[project_name_id]", project_name.id, @project.project_name_id == project_name.id
= project_name

app/views/projects/_sidebar.html.haml
#sidebar
  %ul
    %li
      %h2 Menú
      %ul
        - if controller.action_name == 'index'
          %li
            = link_to 'Nuevo', new_project_path
          %li
            = link_to 'Seguimiento', projects_status_index_path
          - if boss_or_dev_logged_in?
            %li
              = link_to 'Reportes', reports_path
            %li
              = link_to 'Biblioteca', libraries_index_path
        - elsif controller.action_name != 'library'
          %li
            = link_to Project.model_name.human.pluralize.humanize, projects_path
        - if controller.action_name == 'show'
          - unless @project.finished?
            %li
              = link_to 'Editar', edit_project_path(@project)
          %li
            = link_to 'Eliminar', @project, :method => :delete, 
                      :confirm => "¿Está seguro que desea eliminar el #{Project.model_name.human}?"
          %li
            = link_to 'Biblioteca', library_project_path(@project)
          %li
            = link_to Event.model_name.human.humanize.pluralize, project_events_path(@project)
          %li
            = link_to Task.model_name.human.humanize.pluralize, project_tasks_path(@project)
          - if @project.versions.length > 1
            %li
              = link_to 'Replanificación', project_versions_path(@project)
        %li
          = link_to 'Volver', :back
/ end #sidebar

app/views/projects/edit.html.haml
= content_for :sidebar, render('sidebar')

= form_for @project, :html => {:id => 'project_form'} do |f|
  = render f
  
  - unless @project.finished?
    %table.bottom_spaced{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
      %tr
        %td{:width => '50%'}
          %strong= f.label :compl_perc
        %td{:width => '50%'}
          %strong= f.label :envisaged_end_date
      %tr
        %td{:width => '50%'}
          = f.select :compl_perc, options_for_select((0..10).map {|i| [i*10, i*10]}, @project.compl_perc)
        %td{:width => '50%'}
          %table.bottom_spaced{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
            %tr
              %td= f.text_field :envisaged_end_date, :size => 27, :value => date_default_value(@project.envisaged_end_date)
            %tr.hidden{:id => 'notify_envisaged_end_date_changed'}
              %td
                = f.check_box :notify_envisaged_end_date_changed
                Notificar al #{Project.human_attribute_name(:owner_id).downcase }
  
  - if @project.dev == current_user
    %p
      %strong= f.label :status
      %br/
      = f.select :status, options_for_select(Project::Status::SELECT, @project.status)
  = f.submit 'Actualizar'

app/views/projects/index.html.haml
= content_for :sidebar, render('sidebar')

= render 'list', :list => @projects

app/views/projects/library.html.haml
= content_for :sidebar, render('projects/sidebar')

- if @project.library_empty?
  = not_found('archivos')
- else
  %ul
    = render :partial => 'document', :collection => @project.documents

app/views/projects/new.html.haml
= content_for :sidebar, render('sidebar')

= form_for @project, :html => {:id => 'project_form'} do |f|
  = render f
  = f.submit 'Crear'

app/views/projects/show.html.haml
.breadcrumbs.navy [#{@project.status_str} - &#37;#{@project.compl_perc}]
= content_for :sidebar, render('sidebar')

%table.bottom_spaced{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
  %tr
    %td{:width => '50%'}
      %strong= Project.human_attribute_name('project_name_id')
    %td{:width => '50%'}
      %strong= Project.human_attribute_name('org_unit_id')
  %tr
    %td{:width => '50%'}
      = @project
    %td{:width => '50%'}
      = @project.org_unit

%p
  %strong= Project.human_attribute_name('description')
  - if @project.description.present?
    %br/
    = @project.description.humanize

%table.bottom_spaced{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
  %tr
    %td{:width => '33.3%'}
      %strong= Project.human_attribute_name('dev_id')
    %td{:width => '33.3%'}
      %strong= Project.human_attribute_name('owner_id')
    %td{:width => '33.3%'}
      %strong= Project.human_attribute_name('klass')
  %tr
    %td{:width => '33.3%'}
      = @project.dev.name
    %td{:width => '33.3%'}
      = @project.owner.name
    %td{:width => '33.3%'}
      = @project.klass_str

%p
  %strong= Project.human_attribute_name('user_ids')
  %br/
  = @project.users.map{|user| user.name}.join(' - ') 

%table.bottom_spaced{:border => 1, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
  %tr
    %td
      %table{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
        %thead
          %tr
            %td.underlined
              %em Estimación inicial
            %td{:colspan => 2}
        %tbody
          %tr
            %td{:width => '33.3%'}
              %strong Fecha de inicio:
              = l(@project.estimated_start_date)
            %td{:width => '33.3%'}
              %strong Fecha de fin:
              = l(@project.estimated_end_date)
            %td{:width => '33.3%'}
              %strong Duración:
              = duration_desc(@project, :estimated_duration)

%table.bottom_spaced{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
  %tr
    %td.centered
      %strong #{Project.human_attribute_name('envisaged_end_date')}:
      = l(@project.envisaged_end_date)

%table.bottom_spaced{:border => 1, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
  %tr
    %td
      %table{:border => 0, :cellspacing => 0, :cellpadding => 0, :width => "100%"}
        %thead
          %tr
            %td.underlined
              %em Ejecución
            %td{:colspan => 2}
        %tbody
          %tr
            %td{:width => '33.3%'}
              %strong #{Project.human_attribute_name('started_on')}:
              = date_default_value(@project.started_on)
            %td{:width => '33.3%'}
              %strong #{Project.human_attribute_name('ended_on')}:
              = date_default_value(@project.ended_on)
            %td{:width => '33.3%'}
              %strong #{Project.human_attribute_name('actual_duration')}:
              = distance_of_time_in_words(@project.actual_duration) if @project.actual_duration
    
= created_at(@project)
= updated_at(@project)